### ISSUE TITLE
Add parseFloat to numeric parameters

### ISSUE THREAD

**Issue by cthurston** [jawj/MapMarkerAwesome#1]
I created a simple service in Express.js so that I could just load the markers that I wanted from the server, ie "http://localhost/map-marker/fa-times?height=52":

```` javascript
const router = require('express').Router();
const mma = require('../mma')(false);

router.route('/map-marker/:faClass').get(function(req, res, next){
	res.set({'Content-Type': 'image/svg+xml','Cache-Control':'public, max-age=604800'});
	res.send(mma(req.params.faClass, req.query));
});
````

Works beautifully, but I had to add parseFloat to the height because it comes in as a string from the query. 

````javascript
const scale = parseFloat(height) / originalHeight;
````

**Comment by jawj** [comment]
Nice.

I wasn't 100% sure this belonged in the library, but I gave it the benefit of the doubt. It's in.
